theme: jekyll-theme-architect
show_downloads: true
github:
  win_url: https://github.com/neatodev/InstallDebloater/releases/download/1.0.3.2/InstallDebloater-WINDOWS.zip
  linux_url: https://github.com/neatodev/InstallDebloater/releases/download/1.0.3.2/InstallDebloater-LINUX.zip
